### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [Pronoy999/TODOApplication#12]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by Pronoy999** [comment]
Sure. You can create it. Thanks for the help in advance.  You can create the pull request. 
My emailID is:  mukherjee_pronoy@yahoo.in

**Comment by Hamzeto938** [comment]
please review and merge if you like the materials i have sent

**Comment by Hamzeto938** [comment]
and i will also like to create a logo for your application if you are interested.
